server:
  port: 8083

spring:
  application:
    name: idea-service

  profiles:
    active: dev

  config:
    import: "configserver:http://localhost:7090/"  # Pull config from config server

  cloud:
    config:
      uri: http://localhost:7090  # Location of config server

  liquibase:
    drop-first: true

  jpa:
    show-sql: true
